"""
Simple app builder: writes a small HTML/CSS/JS app into sandbox/apps/<slug>.

Returns path of created app (relative to repo root).
"""
from __future__ import annotations
import os
import re
from pathlib import Path

from . import config, utils

logger = utils.logger

def _slugify(name: str) -> str:
    name = name.lower()
    name = re.sub(r'[^a-z0-9]+', '-', name).strip('-')
    return name or "app"

def generate_app(name: str, description: str | None = None) -> str:
    """
    Create a simple todo-like HTML app in the sandbox directory.
    Returns the directory path of the generated app.
    """
    slug = _slugify(name)
    root = Path(config.SANDBOX_DIR).resolve()
    app_dir = root / slug
    app_dir.mkdir(parents=True, exist_ok=True)
    # create index.html, style.css, app.js
    index_html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>{name}</title>
  <link rel="stylesheet" href="./style.css" />
</head>
<body>
  <div class="container">
    <h1>{name}</h1>
    <p class="desc">{description or "Generated by OMNIAI"}</p>
    <input id="taskInput" placeholder="Add a task and press Enter" />
    <ul id="tasks"></ul>
  </div>
  <script src="./app.js"></script>
</body>
</html>
"""
    style_css = """body{font-family: system-ui, Arial; background:#f7f7f9; color:#222}
.container{max-width:720px;margin:40px auto;padding:20px;background:#fff;border-radius:8px;box-shadow:0 6px 20px rgba(0,0,0,0.06)}
h1{margin:0 0 8px}#taskInput{width:100%;padding:10px;margin:12px 0;border:1px solid #ddd;border-radius:4px}
#tasks{list-style:none;padding:0;margin:0}#tasks li{padding:8px 10px;border-bottom:1px solid #eee;display:flex;justify-content:space-between}
.done{opacity:0.6;text-decoration:line-through}
"""
    app_js = """const input = document.getElementById('taskInput');
const list = document.getElementById('tasks');
input.addEventListener('keydown', (e) => {
  if (e.key === 'Enter' && input.value.trim()) {
    const li = document.createElement('li');
    li.textContent = input.value.trim();
    li.addEventListener('click', () => li.classList.toggle('done'));
    list.prepend(li);
    input.value = '';
  }
});
"""
    # Write files
    with open(app_dir / "index.html", "w", encoding="utf-8") as f:
        f.write(index_html)
    with open(app_dir / "style.css", "w", encoding="utf-8") as f:
        f.write(style_css)
    with open(app_dir / "app.js", "w", encoding="utf-8") as f:
        f.write(app_js)
    logger.info("Generated app at %s", app_dir)
    # return relative path
    return str(app_dir)
